export const DEFAULT_TEMPLATES = [
  {
    name: 'Google Frontend',
    type: 'technical',
    role: 'Frontend Engineer',
    company: 'Google',
    difficulty: 'hard',
    duration: 45,
    language: 'english',
    isPublic: true,
  },
  {
    name: 'System Design 45min',
    type: 'system_design',
    role: 'Software Engineer',
    company: null,
    difficulty: 'medium',
    duration: 45,
    language: 'english',
    isPublic: true,
  },
  {
    name: 'Stripe Backend',
    type: 'technical',
    role: 'Backend Engineer',
    company: 'Stripe',
    difficulty: 'hard',
    duration: 60,
    language: 'english',
    isPublic: true,
  },
  {
    name: 'Leadership Behavioral',
    type: 'behavioural',
    role: 'Engineering Manager',
    company: null,
    difficulty: 'medium',
    duration: 30,
    language: 'english',
    isPublic: true,
  },
  {
    name: 'React Live Coding',
    type: 'coding',
    role: 'Frontend Developer',
    company: null,
    difficulty: 'medium',
    duration: 45,
    language: 'english',
    isPublic: true,
  },
  {
    name: 'Mixed - Tech + Behavioral',
    type: 'mixed',
    role: 'Fullstack Engineer',
    company: null,
    difficulty: 'medium',
    duration: 60,
    language: 'english',
    isPublic: true,
  }
];
